on:
  pull_request:
    branches:
      - master
      - '*-release'
    types: [closed]

jobs:
  cherry_pick_3_10_0-release:
    runs-on: ubuntu-latest
    env:
      CPNAME: '3.10.0-release'
    name: Cherry pick into ${{ github.base_ref }}
    if: ${{ contains(github.event.pull_request.labels.*.name, '3.10.0-release') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into ${{ github.base_ref }}
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: $CPNAME
          labels: |
            CP :cherries:
          reviewers: ${{ inputs.author }}
          title: '{old_title} [CP to $CPNAME]'
          body: 'Cherry picking #{old_pull_request_id} onto $CPNAME'
          cherry-pick-branch: ${{ github.head_ref }}_${CPNAME}_CP
          inherit_labels: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
