on:
  pull_request:
    branches:
      - master
      - '*-release'
    types: [opened, closed, labeled, ready_for_review]

jobs:
  cherry_pick_3_10_0-release:
    runs-on: ubuntu-latest
    env:
      CP_branch_name: '3.10.0-release'
    name: Cherry pick into ${{ github.base_ref }}
    if: ${{ contains(github.event.pull_request.labels.*.name, env.CP_branch_name) && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into ${{ github.base_ref }}
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: $CP_branch_name
          labels: |
            CP :cherries:
          reviewers: ${{ inputs.author }}
          title: '{old_title} [CP to ${{CP_branch_name}}]'
          body: 'Cherry picking #{old_pull_request_id} onto ${{CP_branch_name}}'
          cherry-pick-branch: ${{ github.head_ref }}_${{ github.event.label.name }}_CP
          inherit_labels: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
