on:
  pull_request:
    branches:
      - master
      - '*-release' # This matches all branches ending with '-release'
    types: ["closed"]

jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Set branch name from PR labels
        id: set-branch
        run: |
          # Default to empty
          TARGET_BRANCH=""

          # Ensure jq is installed
          sudo apt-get update && sudo apt-get install -y jq

          # Fetch all labels and loop through them
          labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
          echo "Labels on the PR: $labels"

          for label in $labels; do
            echo "Check label: $label"
            case "$label" in
              "master")
                TARGET_BRANCH="master"
                break
                ;;
              *-release)
                TARGET_BRANCH="$label"
                break
                ;;
            esac
          done

          # Fail if no valid branch is found
          if [ -z "$TARGET_BRANCH" ]; then
            echo "No valid branch label (master or *-release) found, exiting."
            exit 1
          fi

          # Set the branch name as an environment variable
          echo "target_branch=$TARGET_BRANCH" >> $GITHUB_ENV
        shell: bash
          
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_PERMISSION }}

      - name: Cherry pick into the target branch
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: ${{ env.target_branch }}
          labels: |
            CP
          reviewers: |
            ${{ github.event.pull_request.user.login }}
          title: '{old_title} [CP to ${{ env.target_branch }}]'
          body: 'Cherry picking #{old_pull_request_id} onto ${{ env.target_branch }}'
          inherit_labels: false
          token: ${{ secrets.BOT_PERMISSION }}
