on:
  pull_request:
    branches:
      - master
      - '*-release'
    types: [opened, closed, labeled, ready_for_review]

jobs:
  cherry_pick_3_10_0-release:
    runs-on: ubuntu-latest
    name: Cherry pick into ${{ github.base_ref }}
    if: ${{ contains(github.event.pull_request.labels.*.name, '3.10.0-release') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into ${{ github.base_ref }}
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: 3.10.0-release
          labels: |
            CP :cherries:
          reviewers: ${{ inputs.author }}
          title: '{old_title} [CP to ${{ github.base_ref }}]'
          body: 'Cherry picking #{old_pull_request_id} onto ${{ github.base_ref }}'
          cherry-pick-branch: ${{ github.head_ref }}_CP_${{ github.base_ref }}
          inherit_labels: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
