on:
  pull_request:
    branches:
      - master
      - 3.8.0-release
      - 3.10.0-release
      - 3.10.1-release
    types: ["closed"]

jobs:
  cherry_pick_3_10_0-release:
    runs-on: ubuntu-latest
    name: Cherry pick into 3.10.0-release
    if: ${{ contains(github.event.pull_request.labels.*.name, '-release') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into 3.10.0-release
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: github.event.pull_request.labels.*.name
          labels: |
            CP
          team-reviewers: |
            nauto/device-sw
          title: '{old_title} [CP to 3.10.0-release]'
          body: 'Cherry picking #{old_pull_request_id} onto 3.10.0-release'
          cherry-pick-branch: cherry-pick-${inputs.branch}-${githubSha}
          inherit_labels: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
