on:
  pull_request:
    branches:
      - master
      - '*-release'
    types: [opened]

jobs:
  cherry_pick_3_10_0-release:
    runs-on: ubuntu-latest
    name: Cherry pick into 3.10.0-release
    if: ${{ contains(github.event.pull_request.labels.*.name, '3.10.0-release') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into 3.10.0-release
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: 3.10.0-release
          labels: |
            CP :cherries:
          reviewers: ${{ inputs.author }}
          title: '{old_title} [CP to 3.10.0-release]'
          body: 'Cherry picking #{old_pull_request_id} onto 3.10.0-release'
          cherry-pick-branch: cp-${{ inputs.branch }}-${{ github.ref_name }}
          inherit_labels: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
